apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: bs4-admin-app-deployment
spec:
  selector:
    matchLabels:
      app: bs4-admin-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: bs4-admin-app
    spec:
      containers:
        - name: bs4-admin-app
          image: fitoni/gitops:31
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service 
metadata: 
  name: bs4-admin-app-service
spec:
  type: NodePort
  selector:
    app: bs4-admin-app
  ports:
    - nodePort: 30163
      port: 8080 
      targetPort: 8080